default: &default
  adapter: postgresql
  encoding: unicode
  database: "leave_development"
  username: "postgres"
  password: "akash"
  host: localhost
  port: 5432
  pool: 8

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

staging:
  <<: *default
